#!/bin/bash
#
# Täisnurkne kolmnurk
#
# loome muutuja nii, et kasutajad sisestavad väärtused ise
echo "Sisesta a-kylje väärtus: "
read a # sellega tekib a muutuja, mille sisse on salvestatud kasutaja väärtus
echo "Sisesta b-kylje väärtus: "
read b
# arvutused
# c = sqrt(a^2+b^2)
c=$(echo "scale=3;sqrt($a^2+$b^2)" | bc) # bc arvutusvalem 
echo "c = $c"
